### ISSUE TITLE
ersip treats "to:" header as comma separated value

### ISSUE THREAD

**Issue by odobenus** [poroh/ersip#17]
If header 'to:'  contains any comma (in the display name, or in the uri (username in  the uri can contain comma)) ,  parsing such sip message leads to error.
For instance parsing

> BYE sip:tt@example.com SIP/2.0
> Via: SIP/2.0/TCP 192.168.1.1
> To: sip:bond,james@example.com
> From: Me <sip:mundane@example.com>;tag=token
> Call-ID: a@b
> CSeq: 139122385 BYE
> Max-Forwards: 255
> Content-Length: 0

fails with message  {error,{header_error,{to,multiple_values}}}

**Comment by poroh** [comment]
RFC 3261 states:
>    It MUST be possible to combine the multiple
>    header field rows into one "field-name: field-value" pair, without
>    changing the semantics of the message, by appending each subsequent
>    field-value to the first, each separated by a comma.  The exceptions
>    to this rule are the WWW-Authenticate, Authorization, Proxy-
>    Authenticate, and Proxy-Authorization header fields.
No exception for From/To headers. So IMO comma need to be escaped in To URI.

**Comment by odobenus** [comment]
ok what about
To: "Bond, James Bond" <sip:some@address.com>

**Comment by odobenus** [comment]
I believe your quote RFC3261 means field can consist of several **valid** field values, separated by comma.  But header cannot be divided by commas before it's parsed. Because it can be splited inside filed value and it makes field value invalid.

**Comment by poroh** [comment]
Agree will fix it.

**Comment by poroh** [comment]
Exact violated RFC 3261 requirement:

>    Multiple header field rows with the same field-name MAY be present in
>    a message **if and only if** the entire field-value for that header field
>    is defined as a comma-separated list (that is, if follows the grammar
>    defined in Section 7.3).
