### ISSUE TITLE
header names must be trimed

### ISSUE THREAD

**Issue by odobenus** [poroh/ersip#18]
the headers like
`To   :   somevalue`
leads to errors. The point is -- spaces after header name, before colon. Parsing returns {error,{header_error,{from,{no_required_header,<<"from">>}}}}

parsed structure contains:

```
{hdr_key,<<"from   ">>} =>
               {header,<<"from   ">>,
                       {hdr_key,<<"from   ">>},
                       [<<"sip:aa@test.ru">>]}
```
it looks like there are some unwanted spaces in the header name

**Comment by poroh** [comment]
`HCOLON  =  *( SP / HTAB ) ":" SWS`

Yes I've missed this SP/HTAB before colon.

**Comment by poroh** [comment]
Fixed by https://github.com/poroh/ersip/commit/d55c84d2c66b30f213b20396b2a633367c7522c6
