### ISSUE TITLE
tag parameter for "to" field can be separated by spaces

### ISSUE THREAD

**Issue by odobenus** [poroh/ersip#21]
the header
`to:  sip:alfa@beta.com     ;    tag=100`
gives  parse erorr (invalid host). I guess it's because it's interpreted as `<sip:alfa@beta.com  ;  tag=100>` (which is invalud sip uri),  but in this case it should be interpreted as `<sip:alfa@beta.com>  ;  tag=100`  (which is valid from/to header, as '; tag = 100' is a header parameter and spaces are allowed).

**Comment by poroh** [comment]
This is because spaces after hostname was interpreted as hostname part.
These spaces appears after splitting by ';'.
