### ISSUE TITLE
non token chars in the display name

### ISSUE THREAD

**Issue by odobenus** [poroh/ersip#26]
`from` and `to` fields can have display name as set  of tokens, or quoted string. That;s why header
```
From: Bond, James  <sip:bond@mi6.uk>
```
should return parse error, as comma is not allowed in the tokens

token is ```1*( alphanum   /   "-"   /   "."   /   "!"   /   "%"   /   "*"   /   "_"   /   "+"   /   "`"   /   "'"   /   "~" ) ```

**Comment by poroh** [comment]
It returns:
added test:
https://github.com/poroh/ersip/commit/6e595581e4d7d6aecd669bfadc7f5ece61c464a9
