### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by ast** [poroh/ersip#45]
Very nice project! I'm working on a WebRTC implementation and use it for SDP.

I'm wondering if there's any plan to implementing ICE (RFC 8445) or if that is outside the scope of this project?

**Comment by poroh** [comment]
Thanks for feedback.

This project is not about media. It is about SIP and SDP. I implement mostly features that I need. Support of attributes related to WebRTC ICE/fingerprint/ssrc maybe in scope but not now.
